### ISSUE TITLE
Error using script

### ISSUE THREAD

**Issue by EasyG0ing1** [wasdin/SWORD-to-JSON#8]
Hello.

I'm not much of a Python user, so I don't really know how to proceed and fix this problem.

The issue is that after installing pysword via ```pip3 install pysword``` this is what happens after cloning the repository and trying to use the script:

```
$python3 sword_to_json.py --source_file KJV.zip --bible_version KJV --output_file KJVNew.json
Traceback (most recent call last):
  File "/Users/michael/Downloads/Bibles/SWORD-to-JSON/sword_to_json.py", line 5, in <module>
    from past.builtins import xrange
ModuleNotFoundError: No module named 'past'
```

I tried removing these two lines:
```
if sys.version_info > (3, 0):
    from past.builtins import xrange
```
But that only made things worse:
```
$python3 sword_to_json.py --source_file KJV.zip --bible_version KJV --output_file KJVNew.json
Traceback (most recent call last):
  File "/Users/michael/Downloads/Bibles/SWORD-to-JSON/sword_to_json.py", line 54, in <module>
    if __name__ == "__main__": main()
  File "/Users/michael/Downloads/Bibles/SWORD-to-JSON/sword_to_json.py", line 51, in main
    bible_dict = generate_dict(args.source_file, args.bible_version)
  File "/Users/michael/Downloads/Bibles/SWORD-to-JSON/sword_to_json.py", line 18, in generate_dict
    for chapter in xrange(1, book.num_chapters+1):
NameError: name 'xrange' is not defined. Did you mean: 'range'?
```
That's when I decided to open this incident...

**Comment by EasyG0ing1** [comment]
OK, I posted too soon. After posting this, I decided to replace xrange with just range, and it finally worked after doing that.

So the fix was to remove these lines

```
if sys.version_info > (3, 0):
    from past.builtins import xrange
```

 and delete the x from xrange in two places.

I'll submit a pull request in case you want to make those changes permanent.
